extends Node

enum AXIS { X, Y }

enum MENU_STATE { START, PAUSE }

enum WINDOW_MODE { FULLSCREEN, WINDOW, BORDERLESS_FS, BORDERLESS_WINDOW }

enum LEVELS { Tutorial }

enum MOVEMENT_ACTION { MOVE, UNDO }

enum PLAYER_FRAMES {
	IDLE,
	BOTTOM,
	LEFT,
	TOP,
	RIGHT,
}

enum DEVICE { KEYBOARD, GAMEPAD }

enum GAME_STATE { START_MENU, PAUSE_MENU, GAME_SELECTION, GAME_ONGOING }
