extends Node

enum AXIS { X, Y }

enum WINDOW_MODE { FULLSCREEN, WINDOW, BORDERLESS_FS, BORDERLESS_WINDOW }

enum LEVELS { Tutorial, Farm, Office, Prison }

enum MOVEMENT_ACTION { MOVE, UNDO }

enum PLAYER_FRAMES {
	IDLE,
	BOTTOM,
	LEFT,
	TOP,
	RIGHT,
}

enum DEVICE { KEYBOARD, GAMEPAD }

enum GAME_STATE {
	SPLASH, START_MENU, PAUSE_MENU, CREDITS, GAME_SELECTION, GAME_ONGOING, GAME_FINISHED
}
